/**
 * js/ai-models.js — Single source of truth for all AI model configurations.
 *
 * Add, remove or edit models HERE and it automatically reflects everywhere:
 *   • Model selector dropdown (built dynamically)
 *   • Status bar labels / badges
 *   • API-key dialog text
 *   • Worker file selection
 *
 * Each entry uses the internal model-id as key (matches data-model in the dropdown).
 */
(function () {
    'use strict';

    window.AI_MODELS = {
        // ── Local: Qwen 3.5 Small (0.8B) ─────────────────────
        'qwen-local': {
            label: 'Qwen 3.5 · Local',
            badge: 'Qwen 3.5 · Local',
            icon: 'bi bi-pc-display',
            statusReady: 'Qwen 3.5 · Local',
            dropdownName: 'Qwen 3.5 Small (0.8B)',
            dropdownDesc: 'Local · Private · ~500 MB download',
            isLocal: true,
            category: 'local-multimodal',
            localModelId: 'textagent/Qwen3.5-0.8B-ONNX',
            downloadSize: '~500 MB',
        },

        // ── Local: Qwen 3.5 Medium (2B) ──────────────────────
        'qwen-local-2b': {
            label: 'Qwen 3.5 2B · Local',
            badge: 'Qwen 3.5 2B · Local',
            icon: 'bi bi-pc-display',
            statusReady: 'Qwen 3.5 2B · Local',
            dropdownName: 'Qwen 3.5 Medium (2B)',
            dropdownDesc: 'Local · Smarter · ~1.2 GB download',
            isLocal: true,
            category: 'local-multimodal',
            localModelId: 'textagent/Qwen3.5-2B-ONNX',
            downloadSize: '~1.2 GB',
        },

        // ── Local: Qwen 3.5 Large (4B) ───────────────────────
        'qwen-local-4b': {
            label: 'Qwen 3.5 4B · Local',
            badge: 'Qwen 3.5 4B · Local',
            icon: 'bi bi-pc-display',
            statusReady: 'Qwen 3.5 4B · Local',
            dropdownName: 'Qwen 3.5 Large (4B)',
            dropdownDesc: 'Local · Best quality · ~2.5 GB · High-end',
            isLocal: true,
            category: 'local-multimodal',
            localModelId: 'textagent/Qwen3.5-4B-ONNX',
            downloadSize: '~2.5 GB',
            requiresHighEnd: true,
        },

        // ── Local: Qwen 3 4B Thinking ────────────────────────
        'qwen3-thinking-4b': {
            label: 'Qwen 3 Thinking · Local',
            badge: 'Qwen 3 Thinking · Local',
            icon: 'bi bi-lightbulb',
            statusReady: 'Qwen 3 4B Thinking · Local',
            dropdownName: 'Qwen 3 Thinking (4B)',
            dropdownDesc: 'Local · Chain-of-thought · ~2.5 GB · High-end',
            isLocal: true,
            category: 'local-thinking',
            localModelId: 'textagent/Qwen3-4B-Thinking-2507-ONNX',
            downloadSize: '~2.5 GB',
            requiresHighEnd: true,
            architecture: 'qwen3',
            dtype: 'q4f16',
        },

        // ── Local: LFM 2.5 1.2B Thinking (Liquid AI) ─────────
        'lfm-thinking-1b': {
            label: 'LFM 1.2B Thinking · Local',
            badge: 'LFM 1.2B Thinking · Local',
            icon: 'bi bi-lightning-charge',
            statusReady: 'LFM 1.2B Thinking · Local',
            dropdownName: 'LFM 1.2B Thinking (Liquid AI)',
            dropdownDesc: 'Local · Blazing fast · WebGPU · ~1.2 GB',
            isLocal: true,
            category: 'local-thinking',
            localModelId: 'textagent/LFM2.5-1.2B-Thinking-ONNX',
            workerFile: 'ai-worker-lfm.js',
            downloadSize: '~1.2 GB',
            requiresWebGPU: true,
            architecture: 'lfm',
            dtype: 'q4',
        },

        // ── Cloud: Groq ────────────────────────────────────────
        'groq-llama': {
            label: 'Llama 3.3 · Groq',
            badge: 'Llama 3.3 · Groq',
            icon: 'bi bi-cloud',
            statusReady: 'Llama 3.3 70B · Groq Cloud',
            workerFile: 'ai-worker-groq.js',
            keyStorageKey: window.MDView.KEYS.API_KEY_GROQ,
            dialogTitle: 'Connect to Groq',
            dialogDesc: 'Enter your free API key to use <strong>Llama 3.3 70B</strong>',
            dialogPlaceholder: 'gsk_xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://console.groq.com/keys',
            dialogLinkText: 'console.groq.com/keys',
            dialogIcon: 'bi bi-cloud',
            dropdownName: 'Llama 3.3 70B',
            dropdownDesc: 'Groq Cloud · Fast · Free tier',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: Google Gemini ───────────────────────────────
        'gemini-flash': {
            label: 'Gemini 3.1 · Google',
            badge: 'Gemini 3.1 · Google',
            icon: 'bi bi-google',
            statusReady: 'Gemini 3.1 Flash Lite · Google',
            workerFile: 'ai-worker-gemini.js',
            keyStorageKey: window.MDView.KEYS.API_KEY_GEMINI,
            dialogTitle: 'Connect to Gemini',
            dialogDesc: 'Enter your free API key to use <strong>Gemini 3.1 Flash Lite</strong>',
            dialogPlaceholder: 'AIzaSy_xxxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://aistudio.google.com/apikey',
            dialogLinkText: 'aistudio.google.com/apikey',
            dialogIcon: 'bi bi-google',
            dropdownName: 'Gemini 3.1 Flash Lite',
            dropdownDesc: 'Google · Fast · Free tier',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: Google Imagen 4 Ultra (Image Generation) ───
        'imagen-ultra': {
            label: 'Imagen 4 Ultra · Google',
            badge: 'Imagen 4 Ultra',
            icon: 'bi bi-image',
            isImageModel: true,
            statusReady: 'Imagen 4 Ultra · Google',
            workerFile: 'ai-worker-imagen.js',
            keyStorageKey: window.MDView.KEYS.API_KEY_GEMINI,
            dialogTitle: 'Connect to Gemini (for Imagen)',
            dialogDesc: 'Enter your Gemini API key to use <strong>Imagen 4 Ultra</strong> image generation',
            dialogPlaceholder: 'AIzaSy_xxxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://aistudio.google.com/apikey',
            dialogLinkText: 'aistudio.google.com/apikey',
            dialogIcon: 'bi bi-image',
            dropdownName: 'Imagen 4 Ultra',
            dropdownDesc: 'Google · Image Generation · 25/day free',
            category: 'cloud-image',
        },

        // ── Cloud: Nano Banana 2 (Gemini 3.1 Flash Image) ─────
        'nano-banana-2': {
            label: 'Nano Banana 2 · Google',
            badge: 'Nano Banana 2',
            icon: 'bi bi-palette',
            isImageModel: true,
            statusReady: 'Nano Banana 2 · Gemini 3.1 Flash Image',
            workerFile: 'ai-worker-gemini-image.js',
            workerModelId: 'gemini-3.1-flash-image-preview',
            keyStorageKey: window.MDView.KEYS.API_KEY_GEMINI,
            dialogTitle: 'Connect to Gemini (for Image Gen)',
            dialogDesc: 'Enter your Gemini API key to use <strong>Nano Banana 2</strong> native image generation',
            dialogPlaceholder: 'AIzaSy_xxxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://aistudio.google.com/apikey',
            dialogLinkText: 'aistudio.google.com/apikey',
            dialogIcon: 'bi bi-palette',
            dropdownName: 'Nano Banana 2',
            dropdownDesc: 'Gemini 3.1 Flash Image · Google',
            category: 'cloud-image',
        },

        // ── Cloud: Stable Diffusion XL (HuggingFace) ──────────
        'hf-sdxl': {
            label: 'SDXL · HuggingFace',
            badge: 'SDXL',
            icon: 'bi bi-brush',
            isImageModel: true,
            statusReady: 'Stable Diffusion XL · HuggingFace',
            workerFile: 'ai-worker-hf-image.js',
            workerModelId: 'stabilityai/stable-diffusion-xl-base-1.0',
            keyStorageKey: window.MDView.KEYS.API_KEY_HF,
            dialogTitle: 'Connect to HuggingFace',
            dialogDesc: 'Enter your free HuggingFace token to use <strong>Stable Diffusion XL</strong> image generation',
            dialogPlaceholder: 'hf_xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://huggingface.co/settings/tokens',
            dialogLinkText: 'huggingface.co/settings/tokens',
            dialogIcon: 'bi bi-brush',
            dropdownName: 'Stable Diffusion XL',
            dropdownDesc: 'HuggingFace · Free tier · Stability AI',
            category: 'cloud-image',
        },

        // ── Cloud: FLUX.1 Schnell (HuggingFace) ──────────────
        'hf-flux': {
            label: 'FLUX.1 Schnell · HuggingFace',
            badge: 'FLUX.1',
            icon: 'bi bi-palette2',
            isImageModel: true,
            statusReady: 'FLUX.1 Schnell · HuggingFace',
            workerFile: 'ai-worker-hf-image.js',
            workerModelId: 'black-forest-labs/FLUX.1-schnell',
            keyStorageKey: window.MDView.KEYS.API_KEY_HF,
            dialogTitle: 'Connect to HuggingFace',
            dialogDesc: 'Enter your free HuggingFace token to use <strong>FLUX.1 Schnell</strong> image generation',
            dialogPlaceholder: 'hf_xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://huggingface.co/settings/tokens',
            dialogLinkText: 'huggingface.co/settings/tokens',
            dialogIcon: 'bi bi-palette2',
            dropdownName: 'FLUX.1 Schnell',
            dropdownDesc: 'HuggingFace · Free tier · Black Forest Labs',
            category: 'cloud-image',
        },

        // ── Cloud: Grok 4.1 Fast via OpenRouter ───────────────
        'openrouter-grok': {
            label: 'Grok 4.1 Fast · xAI',
            badge: 'Grok 4.1 Fast · xAI',
            icon: 'bi bi-lightning-charge',
            statusReady: 'Grok 4.1 Fast · xAI via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'x-ai/grok-4.1-fast',         // override model in worker
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,     // shares same key
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>Grok 4.1 Fast</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-lightning-charge',
            dropdownName: 'Grok 4.1 Fast',
            dropdownDesc: 'xAI · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: Trinity Large via OpenRouter ────────────────
        'openrouter-trinity': {
            label: 'Trinity Large · Arcee',
            badge: 'Trinity Large · Arcee',
            icon: 'bi bi-stars',
            statusReady: 'Trinity Large · Arcee AI via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'arcee-ai/trinity-large-preview:free',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,     // shares same key
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>Trinity Large</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-stars',
            dropdownName: 'Trinity Large',
            dropdownDesc: 'Arcee AI · Free · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: GPT-OSS 20B via OpenRouter ─────────────────
        'openrouter-gpt-oss': {
            label: 'GPT-OSS 20B · OpenAI',
            badge: 'GPT-OSS 20B · OpenAI',
            icon: 'bi bi-cpu',
            statusReady: 'GPT-OSS 20B · OpenAI via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'openai/gpt-oss-20b',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>GPT-OSS 20B</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-cpu',
            dropdownName: 'GPT-OSS 20B',
            dropdownDesc: 'OpenAI · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: Qwen 3.5 Flash via OpenRouter ──────────────
        'openrouter-qwen-flash': {
            label: 'Qwen 3.5 Flash · Alibaba',
            badge: 'Qwen 3.5 Flash · Alibaba',
            icon: 'bi bi-wind',
            statusReady: 'Qwen 3.5 Flash · Alibaba via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'qwen/qwen3.5-flash-02-23',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>Qwen 3.5 Flash</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-wind',
            dropdownName: 'Qwen 3.5 Flash',
            dropdownDesc: 'Alibaba · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: Qwen 3.5 35B-A3B via OpenRouter ────────────
        'openrouter-qwen-35b': {
            label: 'Qwen 3.5 35B · Alibaba',
            badge: 'Qwen 3.5 35B · Alibaba',
            icon: 'bi bi-wind',
            statusReady: 'Qwen 3.5 35B-A3B · Alibaba via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'qwen/qwen3.5-35b-a3b',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>Qwen 3.5 35B</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-wind',
            dropdownName: 'Qwen 3.5 35B-A3B',
            dropdownDesc: 'Alibaba · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: DeepSeek V3.2 via OpenRouter ───────────────
        'openrouter-deepseek': {
            label: 'DeepSeek V3.2 · DeepSeek',
            badge: 'DeepSeek V3.2 · DeepSeek',
            icon: 'bi bi-search',
            statusReady: 'DeepSeek V3.2 · DeepSeek via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'deepseek/deepseek-v3.2',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>DeepSeek V3.2</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-search',
            dropdownName: 'DeepSeek V3.2',
            dropdownDesc: 'DeepSeek · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: Gemini 3.1 Pro Preview via OpenRouter ──────
        'openrouter-gemini-pro': {
            label: 'Gemini 3.1 Pro · Google',
            badge: 'Gemini 3.1 Pro · Google',
            icon: 'bi bi-google',
            statusReady: 'Gemini 3.1 Pro Preview · Google via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'google/gemini-3.1-pro-preview',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>Gemini 3.1 Pro Preview</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-google',
            dropdownName: 'Gemini 3.1 Pro Preview',
            dropdownDesc: 'Google · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: GPT-5.4 via OpenRouter ─────────────────────
        'openrouter-gpt54': {
            label: 'GPT-5.4 · OpenAI',
            badge: 'GPT-5.4 · OpenAI',
            icon: 'bi bi-cpu',
            statusReady: 'GPT-5.4 · OpenAI via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'openai/gpt-5.4',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>GPT-5.4</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-cpu',
            dropdownName: 'GPT-5.4',
            dropdownDesc: 'OpenAI · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: GPT-5.3 Codex via OpenRouter ──────────────
        'openrouter-gpt53-codex': {
            label: 'GPT-5.3 Codex · OpenAI',
            badge: 'GPT-5.3 Codex · OpenAI',
            icon: 'bi bi-code-slash',
            statusReady: 'GPT-5.3 Codex · OpenAI via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'openai/gpt-5.3-codex',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>GPT-5.3 Codex</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-code-slash',
            dropdownName: 'GPT-5.3 Codex',
            dropdownDesc: 'OpenAI · Code · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: Claude Opus 4.6 via OpenRouter ─────────────
        'openrouter-claude-opus': {
            label: 'Claude Opus 4.6 · Anthropic',
            badge: 'Claude Opus 4.6 · Anthropic',
            icon: 'bi bi-chat-dots',
            statusReady: 'Claude Opus 4.6 · Anthropic via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'anthropic/claude-opus-4.6',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>Claude Opus 4.6</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-chat-dots',
            dropdownName: 'Claude Opus 4.6',
            dropdownDesc: 'Anthropic · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: Claude Sonnet 4.6 via OpenRouter ───────────
        'openrouter-claude-sonnet': {
            label: 'Claude Sonnet 4.6 · Anthropic',
            badge: 'Claude Sonnet 4.6 · Anthropic',
            icon: 'bi bi-chat-dots',
            statusReady: 'Claude Sonnet 4.6 · Anthropic via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'anthropic/claude-sonnet-4.6',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>Claude Sonnet 4.6</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-chat-dots',
            dropdownName: 'Claude Sonnet 4.6',
            dropdownDesc: 'Anthropic · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: GPT-5.2 via OpenRouter ─────────────────────
        'openrouter-gpt52': {
            label: 'GPT-5.2 · OpenAI',
            badge: 'GPT-5.2 · OpenAI',
            icon: 'bi bi-cpu',
            statusReady: 'GPT-5.2 · OpenAI via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'openai/gpt-5.2',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>GPT-5.2</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-cpu',
            dropdownName: 'GPT-5.2',
            dropdownDesc: 'OpenAI · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: MiniMax M2.5 via OpenRouter ────────────────
        'openrouter-minimax': {
            label: 'MiniMax M2.5 · MiniMax',
            badge: 'MiniMax M2.5 · MiniMax',
            icon: 'bi bi-box',
            statusReady: 'MiniMax M2.5 · MiniMax via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'minimax/minimax-m2.5',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>MiniMax M2.5</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-box',
            dropdownName: 'MiniMax M2.5',
            dropdownDesc: 'MiniMax · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Cloud: Step 3.5 Flash (Free) via OpenRouter ───────
        'openrouter-step-flash': {
            label: 'Step 3.5 Flash · StepFun',
            badge: 'Step 3.5 Flash · StepFun',
            icon: 'bi bi-lightning',
            statusReady: 'Step 3.5 Flash · StepFun via OpenRouter',
            workerFile: 'ai-worker-openrouter.js',
            workerModelId: 'stepfun/step-3.5-flash:free',
            keyStorageKey: window.MDView.KEYS.API_KEY_OPENROUTER,
            dialogTitle: 'Connect to OpenRouter',
            dialogDesc: 'Enter your API key to use <strong>Step 3.5 Flash</strong> via OpenRouter',
            dialogPlaceholder: 'sk-or-xxxxxxxxxxxxxxxxxxxx',
            dialogLink: 'https://openrouter.ai/keys',
            dialogLinkText: 'openrouter.ai/keys',
            dialogIcon: 'bi bi-lightning',
            dropdownName: 'Step 3.5 Flash',
            dropdownDesc: 'StepFun · Free · via OpenRouter',
            category: 'cloud-text',
            supportsVision: true,
        },

        // ── Local: Granite Docling 258M (IBM) — Document OCR ──
        'granite-docling': {
            label: 'Granite Docling · Local',
            badge: 'Granite Docling · Local',
            icon: 'bi bi-file-earmark-text',
            statusReady: 'Granite Docling 258M · Local',
            dropdownName: 'Granite Docling (258M)',
            dropdownDesc: 'Local · Document OCR → Markdown · ~500 MB',
            isLocal: true,
            category: 'local-document',
            isDocModel: true,
            localModelId: 'textagent/granite-docling-258M-ONNX',
            workerFile: 'ai-worker-docling.js',
            downloadSize: '~500 MB',
        },

        // ── Local: Florence-2 (Microsoft) — Vision OCR & Captioning ──
        'florence-2': {
            label: 'Florence-2 · Local',
            badge: 'Florence-2 · Local',
            icon: 'bi bi-eye',
            statusReady: 'Florence-2 (230M) · Local',
            dropdownName: 'Florence-2 (230M)',
            dropdownDesc: 'Local · OCR + Captioning · ~230 MB',
            isLocal: true,
            category: 'local-document',
            isDocModel: true,
            localModelId: 'textagent/Florence-2-base-ft',
            workerFile: 'ai-worker-florence.js',
            downloadSize: '~230 MB',
        },

        // ── Local: Kokoro 82M TTS (Text-to-Speech) ────────────
        'kokoro-tts': {
            label: 'Kokoro TTS · Local',
            badge: 'Kokoro TTS · Local',
            icon: 'bi bi-volume-up',
            statusReady: 'Kokoro 82M TTS · Local',
            dropdownName: 'Kokoro TTS (82M)',
            dropdownDesc: 'Local · Text-to-Speech · 9 Languages · ~80 MB',
            isLocal: true,
            category: 'local-speech',
            isTtsModel: true,
            localModelId: 'textagent/Kokoro-82M-v1.0-ONNX',
            downloadSize: '~80 MB',
        },

        // ── Local: Voxtral Mini 3B STT (Speech-to-Text, WebGPU) ──
        'voxtral-stt': {
            label: 'Voxtral STT · Local',
            badge: 'Voxtral STT · Local',
            icon: 'bi bi-mic-fill',
            statusReady: 'Voxtral Mini 3B STT · Local',
            dropdownName: 'Voxtral STT (3B)',
            dropdownDesc: 'Local · WebGPU · 13 Languages · ~2.7 GB',
            isLocal: true,
            category: 'local-speech',
            isSttModel: true,
            localModelId: 'textagent/Voxtral-Mini-3B-2507-ONNX',
            downloadSize: '~2.7 GB',
            requiresWebGPU: true,
        },

    };
})();
